name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 🔎
        uses: actions/checkout@v2
      - name: Setup Node.js environment 💻
        uses: actions/setup-node@v2.1.5
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
